tidymodels/workshops

slides/01-introduction.qmd, slides/02-data-budget.qmd, slides/03-what-makes-a-model.qmd, slides/04-evaluating-models.qmd
I found that using unit based sizing yielded suboptimal sizes for small and large screen. This PR switches images that appear on a slide with a title, to use the `![](path)` syntax, and the other background images have had their size specified by percentages.
=> don't use px to set background-size

slides/04-evaluating-models.qmd, slides/06-tuning-hyperparameters.qmd
Closes #31 
@juliasilge could you please re-render both decks for me? As usual, it changes way too many things when I do it 😢 
- Removed talk about parallelism from deck 4. We do a much better job in deck 6 and it doesn't matter much in deck 4
- Updated deck 6 to also mention how to correctly shut down the cluster
- There was also a bug (I guess in revealjs?) where if you have a `fragment` in a column then it won't show up at all, so I removed it. I think it looks fine.
- Updated deck 6 to more correctly shut down the foreach cluster in the teardown chunk
=> Tweaks to discussion about parallelism

slides/03-what-makes-a-model.qmd
They cover the slide title when we use an H1 header
=> Remove hexes when using an H1 header

slides/03-what-makes-a-model.qmd
Because it is natural to talk about these together, rather than talking about what a workflow is in between
@juliasilge does this make sense to you? I was practicing this and it is weird to talk about the modeling workflow capturing both preprocessing and model fitting without having this slide close to it
=> Move bad-workflow image to right after good-workflow image

classwork/02-classwork.qmd, slides/02-data-budget.qmd, slides/03-what-makes-a-model.qmd
Two rearrangements I'm suggesting here:
* Have a "Your turn" for EDA on the frog data first before showing our graphs
* Start with non-stratified sampling, then show stratified sampling after EDA as an example of how EDA could lead to a smarter sampling strategy
=> Re-arranging some of Deck 2 (data budget)

classwork/02-classwork.qmd, slides/02-data-budget.qmd
=> Deck 2 slide + classwork

slides/02-data-budget.qmd
Since #88, the unit of the age column is days @juliasilge
=> One line fix: age days -> seconds in description

docs/slides/02-data-budget.html, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-13-1.svg, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-14-1.svg, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-15-1.svg, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-16-1.svg, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-17-1.svg, docs/slides/02-data-budget_files/figure-revealjs/unnamed-chunk-19-1.svg, slides/02-data-budget.qmd
Closes #120.
Also, uses `scale_fill_viridis()` when `fill = local`, to distinguish from `tip` which has the same factor levels.
=> reverse `tip` factor levels when visualizing

slides/04-evaluating-models.qmd
Using it as a background image meant that the header text overlapped with the taxi so now it's the "main slide content".
=> 2023 NYR Deck 4: tweak taxi image

slides/02-data-budget.qmd, slides/03-what-makes-a-model.qmd, slides/04-evaluating-models.qmd
This PR include references to different stages in the diagram series for the whole game:
- To just the split in train/test at the end of deck 2
- To fitting a decison tree on the training set at the end of deck 3 - with notes to make clear that this was to illustrate the syntax for fitting and we won't actually fit on the entire training set in the whole game
- To resamples after showing the pkgdown site for rsample, before the last exercise on resamples
- To selecting a model before we go into the Final Fit section (which is after the workflow set)
- To the full whole game diagram at the end of deck 4, just before the last slide with end of day discussion
=> Refer back to whole game in decks 2-4

README.md
Closes #193.
While the hosted `index.qmd` is definitely participant-facing, `README.md` feels developer-facing-enough to host these. Fine with me if we opt to keep them elsewhere (or nowhere), though. :)
=> add notes on how to archive a workshop

classwork/03-classwork.qmd
Closes #191.
This was only an issue for the classwork files because the slides don't include that code. plumber pulls up the rapidocs and then hangs when rendering.
=> set `eval = FALSE` for `plumber::pr_run()`

slides/03-what-makes-a-model.qmd
Closes #157. These figure options had been set in other chunks for the same plot, so I just additionally set them here to make the plots the same size when they were previously smaller.
This will be aided by #208, too. :)
=> make size of decision tree plots consistent

slides/intro-02-data-budget.qmd, slides/intro-03-what-makes-a-model.qmd, slides/setup.R
Closes #197.
I chose these with an eye specifically for the `fct_rev(tip)` values, where a tip ("Yes") is green (money🥳) and no tip is red (no money🙃). If you feel we ought to adjust the hue of either of these, feel free to push directly to the branch.
=> set ggplot2 colors

classwork/advanced-02-classwork.qmd, slides/advanced-02-tuning-hyperparameters.qmd
=> add tip to early stopping exercise

slides/advanced-03-racing.qmd
Closes #181.
I thiiink this was the intent of those lines? Initially only highlight lines 1 _through_ 8, rather than 1 _and_ 8, which correspond to the code that makes the grid.
=> fix syntax highlighting

archive/2023-07-nyr/02-data-budget.qmd, archive/2023-07-nyr/03-what-makes-a-model.qmd, archive/2023-07-nyr/04-evaluating-models.qmd, archive/2023-07-nyr/classwork/02-classwork.qmd, archive/2023-07-nyr/classwork/03-classwork.qmd, archive/2023-07-nyr/classwork/04-classwork.qmd
We moved some of the data preprocessing into `modeldatatoo::data_taxi()` as seen here https://github.com/tidymodels/modeldatatoo/pull/28.
For backwards compatibility, This PR uses the old version of the data in the NYR material
Ref https://github.com/tidymodels/workshops/issues/150
=> use versioned taxi data in archive

classwork/advanced-01-classwork.qmd, classwork/advanced-02-classwork.qmd, classwork/advanced-03-classwork.qmd, classwork/advanced-04-classwork.qmd, classwork/intro-02-classwork.qmd, classwork/intro-03-classwork.qmd, classwork/intro-04-classwork.qmd, classwork/intro-extra-recipes-classwork.qmd, index.qmd, slides/advanced-01-feature-engineering.qmd, slides/advanced-02-tuning-hyperparameters.qmd, slides/advanced-03-racing.qmd, slides/advanced-04-iterative.qmd, slides/extras-effect-encodings.qmd, slides/intro-01-introduction.qmd, slides/intro-02-data-budget.qmd, slides/intro-03-what-makes-a-model.qmd, slides/intro-04-evaluating-models.qmd, slides/intro-extra-recipes.qmd, slides/intro-extra-time-splits.qmd, slides/intro-extra-tune.qmd, slides/intro-extra-workflowsets.qmd
With the new version of modeldata, we don't need the other package. 
Also, converted some `size` arguments to `linewidth` to avoid warnings
=> use modeldata instead of modeldatatoo

slides/advanced-01-introduction.qmd, slides/intro-01-introduction.qmd
I don't show CRAN labels as all the packages should be CRAN packages this time
What it looks like currently:
What this PR makes it look like
=> update our versions slide

index.qmd
Having the version there makes it look like that's required to work with the classwork files. Especially with the add-on of "Don’t worry if you haven’t used Quarto before; it will feel familiar to R Markdown users." we don't want to make it look more complicated than it is.
=> Remove Quarto version from classwork section

classwork/advanced-02-classwork.qmd, classwork/advanced-03-classwork.qmd, classwork/advanced-04-classwork.qmd, classwork/advanced-05-classwork.qmd
closes #250
only the number in the title of the classwork qmds were still off, the rest was already updated in https://github.com/tidymodels/workshops/pull/248
=> fix numbering in advanced classwork

slides/advanced-01-introduction.qmd, slides/intro-01-introduction.qmd
With the recent additions, the 3 columns got too long to fit on one slide.
For me, this renders fine for the intro course but looks wonky for the advanced course. Could you render locally and check how they both look for you? I didn't see what could have cause that difference.
=> Update layout of "Our versions" slide to 4 columns

slides/intro-04-evaluating-models.qmd
This PR removes the last slide for deck 4:
This was a "Your turn" slide asking people about their thoughts on the day. That's a leftover from the 2-day format. Now we still have a tuning deck and a dedicated Wrapping Up deck to go in our plan (and the wrapping up deck asks the same question), so I removed that here and end this deck on the whole game diagram.
=> Don't use "end of day discussion" on deck 4 of 6 already

_quarto.yml
The equations look awful with the current version of Quarto (due to a pandoc issue). See https://github.com/quarto-dev/quarto-cli/discussions/3127#discussioncomment-4031511 and https://github.com/quarto-dev/quarto-cli/issues/5636
This PR uses a specific version of mathjax to solve the issue,
=> use mathjax

classwork/extras-vetiver.qmd, classwork/intro-02-classwork.qmd, classwork/intro-03-classwork.qmd, classwork/intro-04-classwork.qmd, classwork/intro-05-classwork.qmd, classwork/intro-extra-recipes-classwork.qmd, slides/extras-vetiver.qmd, slides/intro-02-data-budget.qmd, slides/intro-03-what-makes-a-model.qmd, slides/intro-04-evaluating-models.qmd, slides/intro-05-tuning-models.qmd, slides/intro-extra-recipes.qmd, slides/intro-extra-workflowsets.qmd
A first pass at transitioning from the taxi data to [forested](https://github.com/simonpcouch/forested). 
Tried to mostly stick to finding + replacing for this first PR, dropping `TODO`s where our previous discussion / interpretation needs some reworking. Process was: add `library(forested)` in setup, search for `tip` to make sure there weren't bad substitutions (like "multiple") and then replace with `forested`, replace `taxi` with `forested`.
For the most part, metrics tend to improve in the same situations when they did for the taxi data, so that will save us larger refactorings. That said:
* The outcome classes are much more balanced in this problem, so the `accuracy()` discussion might need some reworking.
* We no longer need to set `cost_complexity` to get a reasonably teachable …
=> transition from `taxi` to `forested`

slides/intro-01-introduction.qmd
closes #315 
With these changes, slide is (eventually) full but not running off the page:
=> shoutout TA in slides

classwork/intro-03-classwork.qmd, slides/intro-03-what-makes-a-model.qmd
Closes #161.
Syncs the slides and classword and rephrases the exercises on the output format of `predict()` + `augment()` to elicit the [prediction guarantee](https://tidymodels.github.io/model-implementation-principles/model-predictions.html) a bit more directly.
=> rephrase exercise on `predict()` + `augment()` output format

slides/intro-03-what-makes-a-model.qmd
closes #303 and closes #294 
So this slide is already pretty full, we essentially have room for one more line. 
Adding the detail about the link function to `glm` makes it spill into an additional line. Adding `brulee` obviously also take a line. So I've opted here for removing `glm` to make room for `brulee`. 
We won't be able to achieve completeness in one slide anyway, our [list of available engines](https://parsnip.tidymodels.org/reference/linear_reg.html) is now way too long! 🎉
=> Update list of possible linear models

slides/intro-02-data-budget.qmd
The row count dropped by 2 when we re-rendered `forested` using the rasters that were "clipped" to Washington rather than the national ones since 2 plots were centered close enough to the border to have non-Washington data--forgot to update that row count here.
=> correct row count of `forested`

slides/annotations.qmd
closes  #302
I'm assuming that the main grid search tuning deck should be deck `3`, see https://github.com/tidymodels/workshops/issues/348
=> Update section name for grid search annotations

index.qmd, slides/advanced-01-introduction.qmd, slides/intro-01-introduction.qmd
For the main site, we should list all of the package requirements (for both sessions). There were a few from the advanced extras that needed to be included. 
For each of the two intro decks, this PR updates the specific packages needed for the session (e.g., intro vs advances). 
@hfrick @simonpcouch Can you update/trim what you need in the intro slide "Let's install some packages"?
=> update packages lists

slides/advanced-01-introduction.qmd, slides/intro-01-introduction.qmd
Follow-up to #357:
The packages to be installed should also show up on the slide "Our versions". 
This is just the quick fix, improving this for the future is captured in #364 .
=> include parallely in "our versions"

slides/intro-04-evaluating-models.qmd
"More on this in Advanced tidymodels!" is a bit of a bummer with the 1-day workshop structure. Since we're gonna be talking about tuning in slide deck 5 now, anyway, let's just refer to then. :)
=> remove reference to Advanced workshop

slides/intro-extra-recipes.qmd
I missed this in #350--`number = 2` referred to `step_dummy()` but, after the changes removing `step_unknown()`, referred to a step that returned zero rows. We're back to returning some interesting-ish results. :)
=> `tidy()` a more interesting step

classwork/intro-02-classwork.qmd, classwork/intro-03-classwork.qmd, classwork/intro-04-classwork.qmd, classwork/intro-05-classwork.qmd, classwork/intro-extra-recipes-classwork.qmd, classwork/intro-extra-workflowsets-classwork.qmd, slides/intro-02-data-budget.qmd, slides/intro-03-what-makes-a-model.qmd, slides/intro-04-evaluating-models.qmd, slides/intro-05-tuning-models.qmd, slides/intro-extra-recipes.qmd, slides/intro-extra-workflowsets.qmd, slides/setup.R
A first pass; just the most basic changes. Will need to make a pass through and make sure that EDA and modeling concepts are still demonstrated as intended.
Prompt:
> This repository contains workshop materials for two tidymodels workshops, intro and advanced.
> 
> I'm working on the introductory workshop. I just made changes to the underlying data from the forested package:
> 
> * The first version of the package just had data from Washington, called `forested`. The second release of the package also includes data from Georgia. The `forested` data is the same as it was, and now is aliased as `forested_wa`. The data from Georgia is called `forested_ga`. The Georgia data has the same structure, except is missing the `northness` variable due to issues with the source raster. `forested_ga` …
=> transition to georgia data in introductory workshop

slides/annotations.qmd, slides/intro-03-what-makes-a-model.qmd
Max mentioned that the many levels of the county factor don't work well in the rpart decision tree.
If we want to tweak the plot (rather than say the number of factor levels in the data or the model choice), we could go with something like this. 
If we want to show people `split_fun()`, we could add it to the annotations.
=> Tweak rpart plot

classwork/intro-04-classwork.qmd, slides/intro-04-evaluating-models.qmd
Adds an exercise on deriving accuracy from TP/FP/FN/TN. 
I considered adding similar ones for specificity/sensitivity, but that seemed too soon after the existing one, and I also considered adding one pre-ROC but that seems too far-fetched.
Vibe check, @hfrick—is the difficulty of this one calibrated reasonably? Is this helpful for understanding?
=> add "Your turn" to derive accuracy
