slides/tidymodels.scss

change fonts

---

docs/search.json
docs/sitemap.xml
docs/slides/01-introduction.html
slides/01-introduction.qmd

Closes #8 
We can change this at the last minute based on the color of sticky notes we get, which [Mine said may not be purple/pink and green](https://rstudio-conf-2022.github.io/workshop-good-practices/instructor.html#have-learners-use-sticky-notes-for-signaling).

Fix slide on using sticky notes

---

docs/search.json
docs/sitemap.xml
docs/slides/01-introduction.html
slides/01-introduction.qmd

Probably @juliasilge needs to re-render with these changes. I seem to have a different version of quarto and different versions of the packages and it changes too much if I try and do it

Minor Deck 1 improvements

---

docs/search.json
docs/sitemap.xml
docs/slides/01-introduction.html
docs/slides/02-data-budget.html
docs/slides/03-what-makes-a-model.html
docs/slides/04-evaluating-models.html
slides/03-what-makes-a-model.qmd
slides/setup.R

Closes #9 
I didn't change the aspect ratio of the hexes but instead raised them up 20px. I think it looks really good now, but it could be adjusted more:

Raise hexes up by 20px

---

docs/search.json
docs/sitemap.xml
docs/slides/02-data-budget.html
slides/02-data-budget.qmd

Again, need @juliasilge to re-render please

Minor revisions for deck 2

---

docs/index.html
docs/search.json
docs/sitemap.xml
index.qmd

Add RStudio version (for Quarto features)

---

docs/index.html
docs/search.json
docs/sitemap.xml
docs/slides/01-introduction.html
index.qmd
slides/01-introduction.qmd

For day 2, plus the "extra" stacks content for day 1

Add more packages

---

slides/01-introduction.qmd
slides/02-data-budget.qmd
slides/03-what-makes-a-model.qmd
slides/04-evaluating-models.qmd

Relevant documentation: https://quarto.org/docs/presentations/revealjs/advanced.html#presentation-size

use 16:9 aspect ratio

---

slides/04-evaluating-models.qmd

Mention the defaults of `rank_results()`

---

slides/03-what-makes-a-model.qmd

Add speaker note about workflow/hardhat level handling

---

slides/02-data-budget.qmd

I can't seem to remember exactly what each variable means, so it seemed like a good place to add a speaker note

Add descriptions about each variable

---

classwork/03-classwork.qmd
slides/02-data-budget.qmd
slides/03-what-makes-a-model.qmd
slides/04-evaluating-models.qmd
slides/05-feature-engineering.qmd
slides/06-tuning-hyperparameters.qmd

This PR adds some (mostly minor) changes from our workshop walkthrough today.

Changes from workshop walkthrough

---

slides/05-feature-engineering.qmd

add seeds to deck 5

---

slides/05-feature-engineering.qmd
slides/annotations.qmd

more on effect encodings

---

slides/05-feature-engineering.qmd

Don't show encoding recipe, and label sequentially for the plot

---

slides/01-introduction.qmd
slides/07-wrapping-up.qmd

Finalize workshop policy/survey slides

---

slides/04-evaluating-models.qmd

I think this looks and reads much better, good idea Dave

Go depth-first into fitting a model with resamples

---

slides/05-feature-engineering.qmd

Based on the discussion in the group meeting @dgrtwo

changes for how we introduce feature engineering and preprocessing

---

slides/annotations.qmd

fix where section 4 starts and some typos

Edits of annotations

---

slides/06-tuning-hyperparameters.qmd

Closes #81 
This PR adds a bit more explanation of how we are using splines, and points out the nonlinear relationships in the data more explicitly.

Explain degrees of freedom

---

classwork/01-classwork.qmd
classwork/03-classwork.qmd
classwork/04-classwork.qmd
classwork/05-classwork.qmd
classwork/06-classwork.qmd
index.qmd
slides/01-introduction.qmd
slides/04-evaluating-models.qmd
slides/05-feature-engineering.qmd
slides/06-tuning-hyperparameters.qmd

Updates to the classwork files to keep them in sync with the slides!
Updates to classwork-2 are pending in #82
"Bonus" content of this PR:
- fix DALEX to DALEXtra 🙈 
- use `abs(coord_y)^2` instead of `coord_y^2` everywhere - it differed between decks 5 and 6 and I think it's a useful quick hint that _both_ coords are symmetric around center ice (we have to use abs(coord_x) in the same line of code already)
- code formatting for readability in the stacks content

Classwork update

---

classwork/02-classwork.qmd
classwork/03-classwork.qmd
classwork/04-classwork.qmd
slides/02-data-budget.qmd
slides/03-what-makes-a-model.qmd
slides/04-evaluating-models.qmd

This makes some of the graphs like the scatterplots and decision trees a little easier to interpret

Turn age to days rather than seconds

---

slides/01-introduction.qmd

Update bit.ly link for rstudio.cloud

---

classwork/02-classwork.qmd
classwork/03-classwork.qmd
classwork/04-classwork.qmd

Staying close to the frog data version, biggest change is probably in the use of the metrics since this is now a classification problem

Update classwork for day 1 to taxi data

---

index.qmd
slides/advanced-03-racing.qmd

Content-only version of #107 (and proper numbering of the section)
Includes revisions from review. 
Closes #107

Racing content files

---

slides/02-data-budget.qmd

closes  #114
@EmilHvitfeldt could you take a look if this is what you had in mind and add/modify as you see fit? 🙌

2023 NYR discuss predictors for taxi data

---

archive/2022-07-RStudio-conf/classwork/01-classwork.qmd
archive/2022-07-RStudio-conf/classwork/02-classwork.qmd
archive/2022-07-RStudio-conf/classwork/03-classwork.qmd
archive/2022-07-RStudio-conf/classwork/04-classwork.qmd
archive/2022-07-RStudio-conf/classwork/05-classwork.qmd
archive/2022-07-RStudio-conf/classwork/06-classwork.qmd

Related to, but does not close, #190.
These contain the contents of the classwork files at https://github.com/tidymodels/workshops/tree/480453634f40bfb16a1fb6ea155f565448d3019e. I wasn't able to get a clean `quarto render` on them, I think due to changes in the nhl data since then.

archive rstudio::conf(2022) classwork

---

slides/04-evaluating-models.qmd

note `collect_*()` functions alongside `collect_metrics()`

---

slides/01-introduction.qmd
slides/02-data-budget.qmd
slides/03-what-makes-a-model.qmd
slides/04-evaluating-models.qmd

Advanced tidymodels seems good-to-go on this front, so I'll leave it be. Closes #130. :)

ensure all chunks have labels

---

slides/advanced-04-iterative.qmd

add "current best" candidate to E/E exercise

---

classwork/advanced-01-classwork.qmd
slides/advanced-01-feature-engineering.qmd

wrap `step_umap(outcome)` in `vars()`

---

classwork/advanced-04-classwork.qmd

load probably in advanced classwork 04

---

slides/01-introduction.qmd

Related to, but does not close, #211. The analogous slide doesn't yet exist for the advanced workshop—a PR fixing #201 can close 211.
We get to hang out with @spcanelon! Yippee!

introduce TAs on slides

---

archive/2022-07-RStudio-conf/05-feature-engineering.qmd
archive/2022-08-Reykjavik-City/05-feature-engineering.qmd
index.qmd
slides/01-introduction.qmd
slides/advanced-01-feature-engineering.qmd

Closes #152.
For my own uses, I definitely prefer pak, but the installation/gitcreds overhead for users who just want to install a couple packages doesn't feel worth it to me.

transition from pak to remotes

---

classwork/advanced-01-classwork.qmd
classwork/advanced-02-classwork.qmd
classwork/advanced-03-classwork.qmd
classwork/advanced-04-classwork.qmd
slides/advanced-01-feature-engineering.qmd
slides/advanced-02-tuning-hyperparameters.qmd
slides/advanced-03-racing.qmd
slides/advanced-04-iterative.qmd
slides/extras-effect-encodings.qmd

Closes #200. Looks like, at least within these slides, we use `_wflow` consistently.

consistent suffix for train and test

---

slides/advanced-01-feature-engineering.qmd

Some super minimal welcome slides for the Advanced workshop. I'll go ahead and merge these, but this likely still needs its own Whole Game setup.
Closes #201. Closes #211. cc @topepo

add welcome slides

---

slides/03-what-makes-a-model.qmd

add additional caution not to `extract_*()` -> `predict()`

---

archive/2022-08-Reykjavik-City/index.qmd
archive/2023-07-nyr/index.qmd

right now the archive pages have some dead links. This PR fixes that

fix links in archive index.qmd files

---

slides/intro-01-introduction.qmd
slides/intro-02-data-budget.qmd
slides/intro-03-what-makes-a-model.qmd
slides/intro-04-evaluating-models.qmd
slides/intro-05-wrapping-up.qmd

The workshops are called "Advanced tidymodels" and "Introduction to tidymodels" per https://posit.co/conference/. This PR changes the subtitles of the intro slides to reflect those names

update subtitles for intro slides

---

README.md

To avoid problems like https://github.com/tidymodels/workshops/pull/219 in the future

Update "how to archive" with linking practices

---

404.qmd

To close https://github.com/tidymodels/workshops/issues/104

add 404 page

---

classwork/intro-03-classwork.qmd

To close https://github.com/tidymodels/workshops/issues/95

change wording

---

classwork/intro-02-classwork.qmd
classwork/intro-03-classwork.qmd
classwork/intro-04-classwork.qmd
slides/intro-02-data-budget.qmd
slides/intro-03-what-makes-a-model.qmd
slides/intro-04-evaluating-models.qmd

To finally close https://github.com/tidymodels/workshops/issues/150

don't prep taxi data

---

slides/intro-02-data-budget.qmd

To close https://github.com/tidymodels/workshops/issues/110
I put it here, since it is right after we first show `set.seed()`

add slide with information about why we use set.seed()

---

classwork/intro-03-classwork.qmd
slides/intro-03-what-makes-a-model.qmd

Using @hfrick's recommendation. :) Closes #156.

refine exercise for defining a model spec

---

index.qmd
slides/advanced-01-feature-engineering.qmd
slides/intro-01-introduction.qmd

Closes #225! I _think_ that embed install is good to go—tested on a posit.cloud instance.

update package list with pkgs for advanced extras

---

slides/intro-extra-tune.qmd

This is a lightweight intro to the very basic concept of "try a bunch of parameters and use the best-performing one". 
We already cover `fit_resamples()` so the step to `tune_grid()` is not very far. Obviously, there is a lot more to tuning but this should get the basic idea across and prepare learners for more sophisticated approaches, either in the advanced course or via e.g. TMwR.

Extra for intro course: tuning

---

index.qmd

Related to, but does not close, #229. Still need to add extra/intro/outro slides. :)

update landing site

---

index.qmd

I accidentally added these back in 😞

remove install stuff for modeldatatoo

---

index.qmd
slides/advanced-06-wrapping-up.qmd

adding outro slides for both courses

---

classwork/intro-04-classwork.qmd
classwork/intro-extra-tune-classwork.qmd
index.qmd
slides/intro-extra-tune.qmd

exercise for tuning extra (intro) slides 

---

classwork/intro-02-classwork.qmd
classwork/intro-04-classwork.qmd
slides/annotations.qmd
slides/intro-02-data-budget.qmd
slides/intro-04-evaluating-models.qmd

closes #179
To be merged once the new versions of rsample and tune are on CRAN.
I haven't put a version requirement in because we don't have that for anything else and it didn't feel crucial but happy to add it if you think that would be better!

Updates for new interface to validation split

---

classwork/intro-01-classwork.qmd
classwork/intro-02-classwork.qmd
classwork/intro-03-classwork.qmd
classwork/intro-04-classwork.qmd
classwork/intro-extra-recipes-classwork.qmd
classwork/intro-extra-tune-classwork.qmd

update subtitle for intro classwork

---

slides/intro-01-introduction.qmd

Touch-ups to deck 1 for intro workshop

---

classwork/extras-vetiver.qmd
classwork/intro-03-classwork.qmd
slides/extras-vetiver.qmd
slides/intro-03-what-makes-a-model.qmd

closes  #167
I've moved the vetiver content into extra material. That also makes it easier to add it in either course. I think it fits a bit better in the advanced one so I've labeled it as advanced in the classwork qmd, but that's obviously not a very hard form of classification! 😄

Move vetiver to extras

---

index.qmd
slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd

We need splines2 for a recipe step in advanced-02-feature-engineering.

Requirements update

---

index.qmd

link to vetiver slides on landing page

---

classwork/intro-03-classwork.qmd
slides/intro-03-what-makes-a-model.qmd

Asking attendees to have a look at other pre-processing option seems like the natural extension here. Do you think this is too broad though?

Extend workflow exercise in intro-deck-3

---

index.qmd

Closes #148.
If others know of a more beginner-facing page that links folks to the right installers, I think that'd be a great switch. :)

link to Rtools in landing page

---

index.qmd

Required for `step_feature_hash()`.

add text2vec to package list

---

classwork/advanced-03-classwork.qmd
classwork/advanced-04-classwork.qmd
classwork/advanced-05-classwork.qmd
slides/advanced-01-introduction.qmd
slides/advanced-03-tuning-hyperparameters.qmd
slides/advanced-04-racing.qmd
slides/advanced-05-iterative.qmd
slides/intro-01-introduction.qmd

This might be related to our server issues and we should probably set it in the notes anyway (as a talking point)

fix lightgbm threads

---

slides/intro-02-data-budget.qmd

A revisiting of #276. This PR instead opts to introduce the source data (including all variables) and modeling problem, _then_ the predictor checklist, so that we can use the predictor checklist to evaluate the variables we have access to and pare down to what we eventually landed on.

taxi data + predictor checklist redux

---

slides/advanced-01-introduction.qmd
slides/advanced-06-wrapping-up.qmd
slides/intro-01-introduction.qmd
slides/intro-06-wrapping-up.qmd

2023 specifics

---

classwork/advanced-01-classwork.qmd
classwork/advanced-02-classwork.qmd
classwork/advanced-03-classwork.qmd
classwork/advanced-04-classwork.qmd
classwork/advanced-05-classwork.qmd
slides/advanced-01-introduction.qmd
slides/advanced-02-feature-engineering.qmd
slides/advanced-03-tuning-hyperparameters.qmd
slides/advanced-04-racing.qmd
slides/advanced-05-iterative.qmd
slides/advanced-06-wrapping-up.qmd
slides/extras-effect-encodings.qmd
slides/extras-transit-case-study.qmd
slides/extras-vetiver.qmd
slides/intro-01-introduction.qmd
slides/intro-02-data-budget.qmd
slides/intro-03-what-makes-a-model.qmd
slides/intro-04-evaluating-models.qmd
slides/intro-05-tuning-models.qmd
slides/intro-06-wrapping-up.qmd
slides/intro-extra-recipes.qmd
slides/intro-extra-time-splits.qmd
slides/intro-extra-workflowsets.qmd

Makes sure that countdown is always loaded. 
Also, the `hotel_rates` data set is modified and keeps the same name. I added `data(hotel_rates)` before the first usages that that errors don't occur if someone runs that first chunk more than once.

Posit 2023 minutia

---

slides/advanced-01-introduction.qmd

rstudio -> Posit
slack -> discord

update for conf

---

slides/intro-01-introduction.qmd

This is to situate rather than summarize the whole game diagram.

Opening to whole game section

---

archive/2024-03-conectaR-spanish/ejercicios/intro-01-ejercicios.qmd
archive/2024-03-conectaR-spanish/ejercicios/intro-02-ejercicios.qmd
archive/2024-03-conectaR-spanish/ejercicios/intro-03-ejercicios.qmd
archive/2024-03-conectaR-spanish/ejercicios/intro-04-ejercicios.qmd
archive/2024-03-conectaR-spanish/ejercicios/intro-05-ejercicios.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-01-introduccion.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-02-presupuesto-de-datos.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-03-partes-del-modelo.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-04-evaluar-modelos.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-05-afinando-modelos.qmd
archive/2024-03-conectaR-spanish/presentacion/intro-06-para-terminar.qmd

Fixed some minor typos in the Spanish version that @edgararuiz prepared for ConectaR2024

Fixed minor typos

---

classwork/intro-04-classwork.qmd

add comment on newly added `cost_complexity`

---

slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd

closes #317 
This leaves out the wifi information, should we add them here or just locally on the day?
The survey link is not yet available, I've opened #328 to keep track of that.

Conf 2024 policies

---

classwork/extras-vetiver.qmd
classwork/intro-02-classwork.qmd
classwork/intro-03-classwork.qmd
classwork/intro-04-classwork.qmd
classwork/intro-05-classwork.qmd
classwork/intro-extra-recipes-classwork.qmd
slides/extras-vetiver.qmd
slides/intro-02-data-budget.qmd
slides/intro-03-what-makes-a-model.qmd
slides/intro-04-evaluating-models.qmd
slides/intro-05-tuning-models.qmd
slides/intro-extra-recipes.qmd
slides/intro-extra-workflowsets.qmd

remove `strata` argument and associated slides

---

slides/annotations.qmd
slides/intro-04-evaluating-models.qmd

closes #310 
It's used in the exercise to demonstrate overfitting, so I didn't add another exercise here.

Intro: Add Brier score

---

_quarto.yml

based on https://positpbc.slack.com/archives/C01LQETLA7L/p1721844041089109?thread_ts=1721827569.007299&cid=C01LQETLA7L 
@EmilHvitfeldt would you review this? I mainly want you to confirm (or deny) that we do mean "everything at the root of the project" here.

Help quarto not be confused anymore

---

classwork/intro-02-classwork.qmd
slides/annotations.qmd
slides/intro-02-data-budget.qmd

move validation set to annotations

---

slides/annotations.qmd
slides/intro-02-data-budget.qmd

Move annotation on `set.seed()`

---

classwork/intro-04-classwork.qmd
classwork/intro-extra-workflowsets-classwork.qmd
slides/intro-extra-workflowsets.qmd

closes #300
The exercise for this deck is a discussion exercise rather than a code exercise but might be nice to have a qmd to poke around in anyways?
I made the classwork use the code from the deck, i.e., not saving the set and results as objects. Should we switch both classwork and deck over to saving the objects?

classwork for workflowsets extra

---

classwork/intro-extra-recipes-classwork.qmd
slides/intro-extra-recipes.qmd

closes #308
I initially started this PR with the intention to make a `forested_raw` dataset that had a date column instead of just the year, so we could preserve something like one of the existing exercises, but ultimately decided against it. A good bit more complexity for a story that's not much more compelling.
So, instead:
* Remove the `step_unknown()`s that are just removed by `step_zv()` right after
* Remove the exercise about the "raw" time variable

revise recipes deck for `forested`

---

slides/advanced-06-wrapping-up.qmd
slides/intro-06-wrapping-up.qmd

Add survey link

---

index.qmd
slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd
slides/setup.R

Update landing page for conf 2024

---

slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd

Add Discord channel name

---

index.qmd

For the advanced slides, which need 1.3.0

check for most recent dials

---

slides/intro-01-introduction.qmd

Using the verbiage from `index.qmd`.

clarify "basic statistical concepts"

---

slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd

Information on locating the gender neutral bathrooms or lactation or prayer rooms doesn't feel like "policies" to me, so splitting up those slides into policies vs. miscellaneous information.

delineate workshop policies vs venue information

---

classwork/advanced-03-classwork.qmd
classwork/advanced-04-classwork.qmd
classwork/advanced-05-classwork.qmd

The changes mostly reflect the use of the new grid function. 
We also changed the model and recipe for iterative search.

updates for new code changes

---

slides/advanced-02-feature-engineering.qmd
slides/advanced-03-tuning-hyperparameters.qmd
slides/annotations.qmd

Mostly links, and annotation, and renumbering.

A few updates to feature engineering and model tuning

---

slides/advanced-02-feature-engineering.qmd

modeldatatoo not used anymore

---

slides/intro-04-evaluating-models.qmd

I find it a lot easier to describe/explain it when I can rely on people seeing it in front of them.

Show ROC curve while decribing it

---

docs/search.json
docs/sitemap.xml
docs/slides/advanced-01-introduction.html
docs/slides/intro-01-introduction.html
slides/advanced-01-introduction.qmd
slides/intro-01-introduction.qmd

make "Asking for help" slide visible

---

README.md

Based on #379 and #291, a follow-up to #196 with some updates reflecting the reality of how this has actually played out in practice.

small tweaks to archiving instructions

---

index.qmd

I'll need the front page docs use pak to install the dev version until it is on CRAN

install forested from Github (for now)

---

slides/intro-04-evaluating-models.qmd

reintroduce slide on dangers of accuracy

---

classwork/intro-04-classwork.qmd
slides/intro-04-evaluating-models.qmd

Show stronger overfitting effect with ROC AUC

---

slides/intro-01-introduction.qmd

This seems to apply here as well: https://github.com/quarto-dev/quarto-cli/issues/12255

fix broken backticks by separating newline

---

slides/intro-01-introduction.qmd

I think this will flow a bit more naturally to me.

Move "Who are you?" to right after "Who are tidymodels?"

---

slides/intro-01-introduction.qmd

This set of slides might change in the meantime, but will go ahead and update the year as a start.

update year in "What is machine learning?" slide

---

index.qmd

add Positron as an IDE option

---

slides/tidymodels.scss

At request from @topepo. This PR updates the styles to increase the font size of the subtitles in the slides.
I didn't rerender with it

increase subtitle font size

---

slides/intro-01-introduction.qmd

add forested to intro deck for intro course
